---
# THIS IS A SAMPLE ".tas.yml" CONFIGURATION FILE
# FIRSTLY - You need to specify which testing framework you are using. Currently supported JS frameworks are : mocha, jest and jasmine.
framework: mocha # mocha # framework should be as per your project

preRun:
  # SECONDLY - You need to set the preRun commands. These are shell commands executed inside the root level of your git repository before running the tests. preRun commands are executed using non-login shells by default, so you must explicitly source any dotfiles as part of the command.
  command:
    - curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc |  apt-key add -
    - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" |  tee /etc/apt/sources.list.d/mongodb-org-4.4.list
    - apt update
    - apt install mongodb-org
    - mongod &
    - yarn install

postMerge:
  # THIRDLY - You need to set postMerge patterns.
  # These would be the glob patterns for the test cases that you want to execute in the post-merge jobs. A postMerge test execution job is initiated whenever a PR is merged into a branch.
  pattern:
    # glob-patterns to discover tests to run in case of postMerge
    - "test/**/*.js"
